### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by MrGallo** [MrGallo/dgaerialimagery#9]
## Waiting for Issue template

- [x] 2023-07-22 Wedding Stock
    - [x] add to issues
    - [x] Check all until keywords
    - [x] Locate video files
- [x] Markham Stock Trailer
- [x] Cardinal Golf (On editing part)
    - [x] Hole 1
    - [x] Hole 2
    - [x] IG Reel
- [x] VMC Hyperlapse (from scratch)
- [x] Holland marsh hyperlapse (from scratch)
- [x] 2023-04-15 VMC hyperlapse and good shots?

- [x] Check how to send proofs to client for selection (watermark? lower quality?)

**Comment by MrGallo** [comment]
## Notes

- Multiple waypoints stitched together into one seamless shot to show the vastness of the property
- Show the different levels of play with the three courses
- Checkout:
  - Cabot Links on Instagram
  - Albatross Images (golf drone)

## Shots

- RedCrest Bistro
  - exterior and interior model
  - FPV flythrough
- Flyovers
  - Fly low, orbit green
  - Ascend over flag/hole
  - No people

Consider showing safety of operation to ease hesitation

Shoot front 9 in the evening
